name: mobx_prueba
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  mobx: ^1.0.0
  flutter_mobx: ^1.0.0
  postgres: ^2.1.0
  edge_alert: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700